### ISSUE TITLE
EXC_BAD on stft function with small values

### ISSUE THREAD

**Issue by manurueda** [dhrebeniuk/RosaKit#10]
Hi Dmytro,

I am trying to replicate some code I have on python using librosa. I am importing the data directly from a JSON, as librosa.load and your main function does not work the same (will open a new ticket).

Code is breaking when computing inside stft function as matrix variable gets rounded to zero when encountering really small values.

Here are my values:
* data array: 150K values in E-03 ~E-04 (negative and positive)
* FFTWindow: 661 values in E-03~E-06 

Matrix -> gets rounded to zeros, so it breaks when trying to execute matrix.rfft

Many thanks

![image](https://user-images.githubusercontent.com/3317934/140859105-e1fdaf16-ca50-43ad-af26-e2200dab5eff.png)

**Comment by dhrebeniuk** [comment]
@manurueda , try please new version from master, I made fixes in PlainPocketFFT

**Comment by manurueda** [comment]
Many thanks. Testing now. Will reply with my review.

**Comment by manurueda** [comment]
The new version is not breaking, but I am still getting a different result from librosa.computeMelSpectrogram. I am seeding the input and comparing the same input on RosaKit and librosa and get different outputs.

I would say that maybe is still related to the low values, on matrix.rfft matrix values are still [Double] 0.0. Here are the initial values in stft (please neglect the error on centered, I mistyped as a 2d array instead of 1d array)

Tomorrow I will do a further checkup comparing both.

![image](https://user-images.githubusercontent.com/3317934/141228980-3199be1d-2362-409f-8836-df9ac6cfce2e.png)

**Comment by dhrebeniuk** [comment]
@manurueda , may you please attach any wav file or data for ability reproduce problem?

**Comment by dhrebeniuk** [comment]
@manurueda , please when available try in master branch
