### ISSUE TITLE
Build Error, Ambiguous use of 'flatMap'

### ISSUE THREAD

**Issue by hohband** [dhrebeniuk/RosaKit#12]
Error when build NoiseReductionExample

/Users/anvsoft/MacProjects/VocalSep/Pods/RosaKit/Sources/Rosa/ArrayLibRosaExtensions.swift:201:44: Ambiguous use of 'flatMap'

XCode Version 11.7 (11E801a)

**Comment by dhrebeniuk** [comment]
@hohband , I'm sorry it's not finished branch, but you can change: 
 "pod 'RosaKit', :path => '../../' " to "    pod 'RosaKit'".
 
 Then it's working.
 
 Now I'm busy with different projects related to "Russian Invasion into Ukraine", russia created many problems for all and me personally,  I will try allocate time when possible for finish tasks for RosaKit.

**Comment by dhrebeniuk** [comment]
@hohband , should be fixed in main
