### ISSUE TITLE
SPM error, complains on mixed languages in package (swift and C)

### ISSUE THREAD

**Issue by Alkenso** [dhrebeniuk/RosaKit#4]

**Comment by dhrebeniuk** [comment]
Hello @Alkenso , hello, thanks for reporting, I know about this error.

Please use CocoaPods, before I'm not fixed this problem.

**Comment by Alkenso** [comment]
FYI: seems you can check approach when you create one SPM target with only C files and another SPM target Swift-only that depends on first one.

**Comment by dhrebeniuk** [comment]
@Alkenso , try use branch swiftPackageManager on adding this library
