### ISSUE TITLE
Add mfcc function

### ISSUE THREAD

**Issue by dhrebeniuk** [dhrebeniuk/RosaKit#7]

**Comment by jinsu35** [comment]
Hi,
is this implemented yet?
also I'm wondering if chroma, contrast, and tonnetz will be available soon.
thanks!

**Comment by dhrebeniuk** [comment]
@jinsu35 , currently istft in progress. After I'm take in work this function.

**Comment by rahul140490** [comment]
Hi, including mfcc feature extraction in this library would be a great help, but I was wondering if first and second derivative of mfcc data can also be included. 
Again, thanks a ton for your work.

**Comment by dhrebeniuk** [comment]
@rahul140490 , I finished istft, so I'm planning mfcc for next release.

**Comment by rahul140490** [comment]
Good to know. But may I know when you're planning the next release? And would you also consider first and second derivatives?

**Comment by dhrebeniuk** [comment]
@rahul140490 , I little bit saw code in librosa, it's used scipy. Thinking how much better use that code.

**Comment by rahul140490** [comment]
There is this project - https://github.com/nahuelproietto/phoneme-recognition-ios/tree/master/BeatVox, which also has mfcc extraction but not second derivative. May be helpful to you.

**Comment by dhrebeniuk** [comment]
@rahul140490 , maybe, but main goal of this project, to be same as librosa in python.

**Comment by rahul140490** [comment]
Yes, I agree. The first and second derivatives of mfcc that I mentioned are part of LibRosa too. Like this - 
mfcc = librosa.feature.mfcc(y=y, sr=sr)
mfcc_delta = librosa.feature.delta(mfcc, order=1)
mfcc_delta2 = librosa.feature.delta(mfcc, order=2)

The delta and delta2 are the first and second derivatives.
So I was requesting you about this functionality if you can please include them too.

**Comment by rahul140490** [comment]
Hi, is it implemented yet?

**Comment by dhrebeniuk** [comment]
@rahul140490 , hello @rahul140490 , not implemented yet.

**Comment by rahul140490** [comment]
I hope it gets implemented soon, kinda in need of something this good and effective for audio preprocessing. 
Thanks in advance and all the best.

**Comment by dhrebeniuk** [comment]
@rahul140490 , I'm trying allocate time for this, it's useful thing for mobile.

**Comment by dhrebeniuk** [comment]
@jinsu35 , @jinsu35 , please try new version 0.0.4, I implemented basic mfcc function, need test it

**Comment by rahul140490** [comment]
thanks a lot.
